### ISSUE TITLE
Verification code expired

### ISSUE THREAD

**Issue by RshmanGit** [RshmanGit/Tryyon-mono-repo#22]
Have been getting this error in the deployed version.

Comment Down if you could point out the cause of the issue. I did not find anything in the logs. 
If we pinpoint the error, create a new branch for this issue from dev and fix it.

<img width="589" alt="Screenshot 2022-06-23 at 9 33 45 AM" src="https://user-images.githubusercontent.com/17221285/175206716-7938aabd-3ebe-49ec-a906-85dcd1bcd76b.png">
<img width="589" alt="Screenshot 2022-06-23 at 9 33 45 AM" src="https://user-images.githubusercontent.com/17221285/175206725-7f1116fc-d2fa-4410-b44b-0dedb0576644.png">

**Comment by ankitgdes** [comment]
That's because of the verification expiry. Are you trying to verify a new user or old one?

**Comment by ankitgdes** [comment]
Have added new commits to #20 to fix this issue

**Comment by RshmanGit** [comment]
Resolved and tested
